server:
  port: 8081

#打开自定义starter配置
self:
  enabled: true
#配置数据源
driverName: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://127.0.0.1:3306/orange?serverTimezone=UTC
user: root

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orange?serverTimezone=UTC
    hikari:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      #空闲连接存活最大时间 2分钟（默认是10分钟）
      idle-timeout: 120000
      #连接池最大连接数
      maximum-pool-size: 10
      auto-commit: true
      pool-name: FirstHikariCP
      #控制连接池中连接最长生命周期这里设置了20分钟
      max-lifetime: 120000
      #连接数据库超时时间
      connection-timeout: 30000
      connection-test-query: select 1
